import Head from "next/head";
import Footer from "../components/Footer.js";
import LineChart from "../components/LineChart.js";
import clientPromise from "../lib/mongodb";

export default function Home({ dataSets }) {
  console.log(dataSets);
  return (
    <div>
      <Head>
        <title>Fiodl - Hodl Your Fiat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-full justify-center">
        <LineChart />
      </main>
      <Footer />
    </div>
  );
}

export async function getStaticProps() {
  try {
    await clientPromise;
    //   const res = await fetch("url");
    //   const data = await res.json();
    return {
      props: {
        dataSets: "hello",
      },
      revalidate: 60 * 60 * 24 * 1, // seconds * Minutes * hours = 1 day
    };
  } catch (err) {
    console.error(err);
  }
}
