import Head from "next/head";
import Footer from "../components/Footer.js";
import LineChart from "../components/LineChart.js";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fiodl - Hodl Your Fiat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-full justify-center">
        <LineChart />
      </main>
      <Footer />
    </div>
  );
}
