import Head from "next/head";
import Footer from "../components/Footer.js";
import LineChart from "../components/LineChart.js";
import clientPromise from "../lib/mongodb";

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Fiodl - Hodl Your Fiat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-full justify-center">
        <LineChart bankData={props} />
      </main>
      <Footer />
    </div>
  );
}

export async function getStaticProps() {
  try {
    const client = await clientPromise;
    const db = client.db("rates");
    let props = { dates: [] };

    let collections = await db.listCollections().toArray();
    collections.forEach(collection => (props[collection.name] = {}));

    for (let bank in props) {
      const collection = db.collection(bank);
      let documents = await collection.find({}, {}).toArray();
      bank !== "dates" && (props[bank].rates = []);

      documents.forEach(document => {
        bank === "discovers" && props.dates.push(Date.parse(document.createdAt));
        !props[bank].type && (props[bank].type = document.type);
        props[bank].rates.push(document.rate);
      });
    }

    return {
      props,
      revalidate: 60 * 60 * 24 * 1, // seconds * Minutes * hours = 1 day
    };
  } catch (err) {
    console.error(err);
  }
}
